### ISSUE TITLE
Error while generate dropper server

### ISSUE THREAD

**Issue by tugdualnicolas** [D4Vinci/Dr0p1t-Framework#16]
Running on a Debian 8 VPS
All requirement is installed, wine too. 
```

+ Received command : python Dr0p1t.py  https://f****/uploads/********exe 
+ After validation : python Dr0p1t.py https://f****/uploads/********exe 
+ Exe generated!
[2017-07-02 18:07:25,734] ERROR in app: Exception on /params [POST]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1518, in handle_user_exception
    return handler(e)
  File "Dr0p1t_Server.py", line 142, in exceptions
    return abort(500)
  File "/usr/lib/python2.7/dist-packages/werkzeug/exceptions.py", line 707, in abort
    return _aborter(status, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/werkzeug/exceptions.py", line 687, in __call__
    raise self.mapping[code](*args, **kwargs)
InternalServerError: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.
```

**Comment by D4Vinci** [comment]
Could you show me server.log file content?

**Comment by tugdualnicolas** [comment]
```

--------------------
[2017-Jul-02 18:05] 86.214.68.96 GET http /? 200 OK
--------------------
[2017-Jul-02 18:06] 86.214.68.96 POST http /params? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "Dr0p1t_Server.py", line 118, in params
    blah = os.rename( os.path.join( "output",file_name ),os.path.join( "static","data","install_flashplayer.exe" ) )
OSError: [Errno 2] No such file or directory

--------------------
[2017-Jul-02 18:07] 86.214.68.96 GET http /? 200 OK
--------------------
[2017-Jul-02 18:07] 86.214.68.96 POST http /params? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "Dr0p1t_Server.py", line 118, in params
    blah = os.rename( os.path.join( "output",file_name ),os.path.join( "static","data","install_flashplayer.exe" ) )
OSError: [Errno 2] No such file or directory

--------------------
[2017-Jul-02 18:13] 86.214.68.96 POST http /params? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "Dr0p1t_Server.py", line 118, in params
    blah = os.rename( os.path.join( "output",file_name ),os.path.join( "static","data","install_flashplayer.exe" ) )
OSError: [Errno 2] No such file or directory

```

**Comment by D4Vinci** [comment]
try to use Dr0p1t itself and show me what happens

**Comment by tugdualnicolas** [comment]
It create the dropper but it do not work. Look at new issue #17
