### ISSUE TITLE
Error in compiling the final file to exe

### ISSUE THREAD

**Issue by nourziady** [D4Vinci/Dr0p1t-Framework#2]
when i try to make the dropper i got this error

> Traceback (most recent call last):
  File "Dr0p1t.py", line 185, in <module>
    main()
  File "Dr0p1t.py", line 174, in main
    make_copy( os.path.join("temp","dist",file_name),os.path.join("output",file_name) )
  File "Dr0p1t.py", line 43, in make_copy
    old_file = open( old,"rb" )
FileNotFoundError: [Errno 2] No such file or directory: 'temp\\dist\\Your_daily_malware_50.exe' <

i'm running windows 10 and i used it with administrator privileges

**Comment by D4Vinci** [comment]
That's because pyinstaller didn't compiled the script for some reason
You can try removing "--noconsole" from the varaible command in the main script "Dr0p1t.py" or wait for my fix I will handle this and let you know
In meanwhile if you want to help, you can replace the lines 164,165,166 in Dr0p1t.py with the following line and show me the output : 
`        p  = subprocess.call( command.format(file_name+".py") )`
Best regards

**Comment by nourziady** [comment]
> Traceback (most recent call last):
  File "c:\users\pitns\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\pitns\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\PiTnS\AppData\Local\Programs\Python\Python36-32\Scripts\pyinstaller.exe\__main__.py", line 9, in <module>
  File "c:\users\pitns\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\pitns\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\pitns\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\building\build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\pitns\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\building\build_main.py", line 734, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "c:\users\pitns\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\building\build_main.py", line 212, in __init__
    self.__postinit__()
  File "c:\users\pitns\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\building\datastruct.py", line 161, in __postinit__
    self.assemble()
  File "c:\users\pitns\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\building\build_main.py", line 317, in assemble
    excludes=self.excludes, user_hook_dirs=self.hookspath)
  File "c:\users\pitns\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\depend\analysis.py", line 560, in initialize_modgraph
    graph.import_hook(m)
  File "c:\users\pitns\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1509, in import_hook
    source_package, target_module_partname, level)
  File "c:\users\pitns\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1661, in _find_head_package
    target_module_headname, target_package_name, source_package)
  File "c:\users\pitns\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\depend\analysis.py", line 209, in _safe_import_module
    module_basename, module_name, parent_package)
  File "c:\users\pitns\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2077, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "c:\users\pitns\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2167, in _load_module
    self._scan_code(m, co, co_ast)
  File "c:\users\pitns\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2585, in _scan_code
    module, module_code_object, is_scanning_imports=False)
  File "c:\users\pitns\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2831, in _scan_bytecode
    global_attr_name = get_operation_arg_name()
  File "c:\users\pitns\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2731, in get_operation_arg_name
    return module_code_object.co_names[co_names_index]
IndexError: tuple index out of range
Traceback (most recent call last):
  File "Dr0p1t.py", line 183, in <module>
    main()
  File "Dr0p1t.py", line 172, in main
    make_copy( os.path.join("temp","dist",file_name),os.path.join("output",file_name) )
  File "Dr0p1t.py", line 43, in make_copy
    old_file = open( old,"rb" )
FileNotFoundError: [Errno 2] No such file or directory: 'temp\\dist\\Your_daily_malware_2.exe'<

**Comment by D4Vinci** [comment]
The reason of the error is you are using python 3.6 and it's not supported by pyinstaller yet ! [See](https://github.com/pyinstaller/pyinstaller/issues/2329).

As you can see the error is not from the framework ,so you have two solutions : 
1. Switch back to python 3.5 and the framework will work fine.
2. Wait until pyinstaller support 3.6 version :smile:

Thank you for your concern

**Comment by nourziady** [comment]
Thanks :) gonna try switching back

**Comment by nourziady** [comment]
Thank you, its workin good with python 3.5.3

**Comment by D4Vinci** [comment]
You are welcomed, have fun ;)
