### ISSUE TITLE
InternalServerError: 500

### ISSUE THREAD

**Issue by materaj** [D4Vinci/Dr0p1t-Framework#21]
I don't sure what happening but when I tried to use Dr0p1t_Server.py. It always return 500 Internal Server Error after I tried to create dropper with Web GUI

<img width="1654" alt="screen shot 2560-07-09 at 20 36 48" src="https://user-images.githubusercontent.com/818806/27994364-89e021b8-64e6-11e7-8037-b8f2ecebdfad.png">

**Comment by D4Vinci** [comment]
What's in server.log file ?

**Comment by materaj** [comment]
--------------------
[2017-Jul-09 20:33] 127.0.0.1 GET http /? 200 OK
--------------------
[2017-Jul-09 20:33] 127.0.0.1 GET http /? 200 OK
--------------------
[2017-Jul-09 20:34] 127.0.0.1 POST http /params? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "Dr0p1t_Server.py", line 118, in params
    blah = os.rename( os.path.join( "output",file_name ),os.path.join( "static","data","install_flashplayer.exe" ) )
OSError: [Errno 2] No such file or directory

--------------------
[2017-Jul-09 20:34] 127.0.0.1 GET http /params? 405 METHOD NOT ALLOWED

**Comment by D4Vinci** [comment]
Try to use Dr0p1t itself with this commands

**Comment by 3206614665** [comment]
一大堆bug，跑不起来

**Comment by D4Vinci** [comment]
while there's no response I will consider this as solved !!

**Comment by materaj** [comment]
Because you not mention any command

<img width="808" alt="screen shot 2560-07-24 at 08 19 02" src="https://user-images.githubusercontent.com/818806/28504944-e07b52be-7048-11e7-8383-edd93a8632a9.png">
