### ISSUE TITLE
parameter error

### ISSUE THREAD

**Issue by hostbob** [D4Vinci/Dr0p1t-Framework#28]
i got this error when generating via server
![errir](https://user-images.githubusercontent.com/7292467/29771877-d18a0822-8baa-11e7-934e-3c9ad5b31ebd.png)
![param](https://user-images.githubusercontent.com/7292467/29771878-d18a6b0a-8baa-11e7-9b14-899df28b3d25.png)

Kindly advice which one i am not doing right

**Comment by D4Vinci** [comment]
What's the output of server.log and cmd.log files ?

**Comment by hostbob** [comment]
--------------------
[2017-Aug-28 08:31] 177.153.13.16 GET http /? 200 OK
--------------------
[2017-Aug-28 08:31] 177.153.13.16 GET http /favicon.ico? 404 NOT FOUND
--------------------
[2017-Aug-28 08:32] 177.153.13.16 POST http /params? 200 OK
--------------------
[2017-Aug-28 08:33] 177.153.13.16 POST http /params? 200 OK
--------------------
[2017-Aug-28 08:34] 177.153.13.16 POST http /params? 200 OK
--------------------
[2017-Aug-28 08:37] 177.153.13.16 POST http /params? 200 OK


CMD.LOG


C:\Python34\lib\site-packages\win_unicode_console\__init__.py:31: RuntimeWarning: sys.stdin.encoding == 'utf-8', whereas sys.stdout.encoding == 'cp1252', readline hook consumer may assume they are the same

  readline_hook.enable(use_pyreadline=use_pyreadline)

Traceback (most recent call last):

  File "C:\Python34\Scripts\Dr0p1t.py", line 310, in <module>

    main()

  File "C:\Python34\Scripts\Dr0p1t.py", line 96, in main

    prepare_folder("temp")

  File "C:\Python34\Scripts\Dr0p1t.py", line 87, in prepare_folder

    xx = os.mkdir(folder)

FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'temp'

**Comment by D4Vinci** [comment]
Ok I don't know why it didn't delete temp folder but if you deleted it before running everything will be fine

**Comment by hostbob** [comment]
i believe you meant temp is Dr0pIt folder. so i deleted the temp in Dr0pIt folder than this error occured

![drop](https://user-images.githubusercontent.com/7292467/29775171-eda3ec72-8bb8-11e7-9cd3-c27f3f44b6f6.png)


and this is the SERVER.LOG output


--------------------
[2017-Aug-28 10:16] 177.153.13.16 GET http /? 200 OK
--------------------
[2017-Aug-28 10:16] 177.153.13.16 POST http /params? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python34\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Python34\Scripts\Dr0p1t_Server.py", line 118, in params
    blah = os.rename( os.path.join( "output",file_name ),os.path.join( "static","data","install_flashplayer.exe" ) )
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'output\\Dr0pp1r71' -> 'static\\data\\install_flashplayer.exe'

--------------------
[2017-Aug-28 10:17] (MYIP HIDDEN) POST http /params? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python34\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Python34\Scripts\Dr0p1t_Server.py", line 118, in params
    blah = os.rename( os.path.join( "output",file_name ),os.path.join( "static","data","install_flashplayer.exe" ) )
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'output\\Dr0pp1r29' -> 'static\\data\\install_flashplayer.exe'

**Comment by D4Vinci** [comment]
Please remove Dr0p1t folder and then install it like in this tutorial :
https://youtu.be/A7r1rKlAHZg

**Comment by hostbob** [comment]
I keep getting error when installing can u share ur Kali repository?

**Comment by D4Vinci** [comment]
It's the normal repo

**Comment by D4Vinci** [comment]
Also try to check if data folder exist in static folder

**Comment by hostbob** [comment]
no data folder in static folder

Image as attached


![kal](https://user-images.githubusercontent.com/7292467/29858742-b26528f4-8d13-11e7-8352-c3d350f1a146.png)

**Comment by D4Vinci** [comment]
Create it and the problem will be solved

**Comment by hostbob** [comment]
no use bro, i create data folder in static folder. and got this error using Dr0p1t_Server.py

Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

AND 

this when using TERMINAL

 [!] PyInstaller not installed : Can't compile file to exe..
 [*] Finished and saved our Dr0pp3r as Dr0pp1r42 in output folder ( happy hunting )

**Comment by hostbob** [comment]
How i wish i can lay my hand on this tool

**Comment by D4Vinci** [comment]
I made a tutorial about Dr0p1t-Server yesterday, it should help you...
https://www.youtube.com/watch?v=zuU4MUaHLkM

**Comment by D4Vinci** [comment]
I made a tutorial about Dr0p1t-Server yesterday, it should help you...
https://www.youtube.com/watch?v=zuU4MUaHLkM
